### ISSUE TITLE
Check Length output file

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/scilla#19]
When typed `scilla dns -target d`

```
target: d
=============== DNS SCANNING ===============
panic: runtime error: slice bounds out of range [-4:]

goroutine 1 [running]:
main.lookupDNS(0x7ffcb04c527f, 0x1, 0x0, 0x0)
	/home/edoardottt/github/scilla/scilla.go:1016 +0x1066
main.execute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9c51b0, 0x0, ...)
	/home/edoardottt/github/scilla/scilla.go:168 +0x723
main.main()
	/home/edoardottt/github/scilla/scilla.go:125 +0x79

```

**Comment by edoardottt** [comment]
done
